<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eo</string>
	</array>
	<key>keyEquivalent</key>
	<string>^@E</string>
	<key>name</key>
	<string>EO</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\+.*\n</string>
			<key>name</key>
			<string>meta.tag.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*\n</string>
			<key>name</key>
			<string>comment.line.eo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s(&gt;) (?=[[:alpha:]_][[:alnum:]_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.eo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.binding.eo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[[:alpha:]_][[:alnum:]_-]*)</string>
					<key>contentName</key>
					<string>entity.name.function</string>
					<key>end</key>
					<string>(?![[:alnum:]_-])</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\s[+-]?\d+(\.\d+)?(e[+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.float.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[+-]?\d+|0x[a-f\d]+\b</string>
			<key>name</key>
			<string>constant.numeric.int.eo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>constant.character.eo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[\dA-F][\dA-F](-[\dA-F][\dA-F])*\b</string>
			<key>name</key>
			<string>constant.numeric.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@</string>
			<key>name</key>
			<string>keyword.other.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&gt;</string>
			<key>name</key>
			<string>keyword.operator.assignment.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|seq|while)\b</string>
			<key>name</key>
			<string>keyword.control.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(memory|cage)\b</string>
			<key>name</key>
			<string>keyword.other.directive.eo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(eq|geq|greater|leq|less|neq|add|sub|mul|div|mod|pow|neg|not)\b</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.eo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eo</string>
	<key>uuid</key>
	<string>13C2CA63-1F12-4765-B4B7-84B1C795A7B0</string>
</dict>
</plist>
