<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eo</string>
	</array>
	<key>keyEquivalent</key>
	<string>^@E</string>
	<key>name</key>
	<string>EO</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\+.*\n</string>
			<key>name</key>
			<string>meta.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.*\n</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s[+-]?\d+(\.\d+)?(e[+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.float</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[+-]?\d+|0x[a-f\d]+\b</string>
			<key>name</key>
			<string>constant.numeric.int</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>constant.character</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[\dA-F][\dA-F](-[\dA-F][\dA-F])*\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&gt;</string>
			<key>name</key>
			<string>keyword.operator.assignment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|seq|while)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(memory)\b</string>
			<key>name</key>
			<string>keyword.other.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(eq|geq|greater|leq|less|neq|add|sub|mul|div|mod|pow|neg|not)\b</string>
			<key>name</key>
			<string>keyword.operator.arithmetic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eo</string>
	<key>uuid</key>
	<string>13C2CA63-1F12-4765-B4B7-84B1C795A7B0</string>
</dict>
</plist>
